<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ArSclStudio.Engine</AssemblyName>
    <RootNamespace>ArSclStudio.Engine</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ArSclStudio.Engine.Tests" />
    <ProjectReference Include="../ArSclStudio.Scl/ArSclStudio.Scl.csproj" />
  </ItemGroup>
</Project>

