namespace ArSclStudio.Scl.Semantics;

public enum SclSemanticKind
{
    Document = 0,
    Header,
    Substation,
    Communication,
    SubNetwork,
    ConnectedAccessPoint,
    GseCommunication,
    Address,
    Ied,
    Services,
    AccessPoint,
    Server,
    LogicalDevice,
    LogicalNodeZero,
    LogicalNode,
    DataSet,
    Fcda,
    ReportControl,
    LogControl,
    GseControl,
    SampledValueControl,
    Inputs,
    ExternalReference,
    SettingGroupControl,
    Doi,
    Sdi,
    Dai,
    DataTypeTemplates,
    LogicalNodeType,
    DataObjectType,
    DataAttributeType,
    EnumerationType,
    DataObjectDefinition,
    SubDataObjectDefinition,
    DataAttributeDefinition,
    BasicDataAttributeDefinition,
    Private
}
