namespace ArSclStudio.Engine.Navigation;

public enum ExplorerNodeKind
{
    Document = 0,
    Group,
    Header,
    Substation,
    Communication,
    SubNetwork,
    ConnectedAccessPoint,
    Address,
    Ied,
    Services,
    AccessPoint,
    Server,
    LogicalDevice,
    LogicalNode,
    DataSet,
    DataSetMember,
    ReportControl,
    LogControl,
    GseControl,
    SampledValueControl,
    Inputs,
    ExternalReference,
    SettingGroupControl,
    DataObjectInstance,
    SubDataInstance,
    DataAttributeInstance,
    DataTypeTemplates,
    LogicalNodeType,
    DataObjectType,
    DataAttributeType,
    EnumerationType,
    DataObjectDefinition,
    SubDataObjectDefinition,
    DataAttributeDefinition,
    BasicDataAttributeDefinition,
    Private,
    XmlElement,
    XmlAttribute,
    XmlText,
    XmlComment,
    XmlProcessingInstruction,
    XmlOther
}
